### ISSUE TITLE
VIDEOJS: ERROR: The "Flvjs" tech is undefined. Skipped browser support check for that tech.

### ISSUE THREAD

**Issue by hxl-dy** [mister-ben/videojs-flvjs#1]

**Comment by mister-ben** [comment]
Ensure you'd added both FLV.js and the plugin as the example in the readme. If you still have a problem, please a reduced test case in order to replicate.

**Comment by hxl-dy** [comment]
it's because the loading order. i fix it. thank you all the same.
but. i wonder if there's an option to pass option of flv.js, like this https://github.com/hxl-dy/videojs-flvjs/commit/132dfcef7b9216f3851d0ba91b5e19d64cc4eb8f

**Comment by mister-ben** [comment]
It makes sense to pass options, but I probably wouldn't get to it for a while. If you're up for adding that functionality, a PR would be welcome.

**Comment by hxl-dy** [comment]
Okay. i will try my best, thankyou.

**Comment by mister-ben** [comment]
Cool. I guess as well as options passed as tech options, we might need to be able to configure some options per-source, e.g. your `hasAudio` example.

**Comment by dragonishare** [comment]
> it's because the loading order. i fix it. thank you all the same.
> but. i wonder if there's an option to pass option of flv.js, like this [hxl-dy@132dfce](https://github.com/hxl-dy/videojs-flvjs/commit/132dfcef7b9216f3851d0ba91b5e19d64cc4eb8f)

when I tried to integrate into the react test, I also encountered this problem. The problem of the load order you mentioned is not very understandable.

**Comment by hxl-dy** [comment]
@dragonishare

**Comment by hxl-dy** [comment]
@dragonishare 
the loading order should be video.js, flv.js, videojs-flvjs.

**Comment by dragonishare** [comment]
> @dragonishare
> the loading order should be video.js, flv.js, videojs-flvjs.

@hxl-dy I did, but the problem is still there. How did you fix this problem? --"VIDEOJS: ERROR: The "Flvjs" tech is undefined"

**Comment by dragonishare** [comment]
refer to readme, it works when I use it directly through script tag in html, but when used in react with npm. , it doesn't work, throw 'VIDEOJS: ERROR: The "Flvjs" tech is undefined. Skipped browser support check for that tech.'

**Comment by hxl-dy** [comment]
Maybe, you forgot assign the flv.js to global window like `window.flvjs = require('flv.js/dist/flv');`.
