### ISSUE TITLE
Fast forward video no option request.

### ISSUE THREAD

**Issue by mazili** [mister-ben/videojs-flvjs#28]
When i fast forward the video about 5 minutes,the video is always loading. The flvjs document says that an option request will be sent when fast forward video , i used in my demo but it didn't send a request.Is it a question?Looking forward to reply.Thanks!

**Comment by mister-ben** [comment]
Hi, the actual seekingis handled by flv.js, you should ask there instead. Video.js just passes on the requested currentTime to the video element, and flv.js responds to that.
