### ISSUE TITLE
New version update of VideoJS

### ISSUE THREAD

**Issue by Chhunneng** [mister-ben/videojs-flvjs#29]
I'm not sure this issue happened because new version of videoJS or not please can you check?

<img width="847" alt="Screenshot 2023-02-01 at 12 24 57 PM" src="https://user-images.githubusercontent.com/47348453/215973666-09032d3b-fb51-4bc5-9c15-b4bb9cf1cc81.png">

**Comment by mister-ben** [comment]
This plugin won't work with video.js 8 as it is, as the build transpiles classes.

**Comment by mister-ben** [comment]
0.3.1 works with v8
