### ISSUE TITLE
player.flvjs is not a function

### ISSUE THREAD

**Issue by avinlakhera** [mister-ben/videojs-flvjs#3]
var videojs = require('video.js');
 
// The actual plugin function is exported by this module, but it is also 
// attached to the `Player.prototype`; so, there is no need to assign it 
// to a variable. 
require('videojs-flvjs');
 
var player = videojs('my-video');
 
player.flvjs();

I am using the test code mentioned in readme I am getting "player.flvjs is not a function" error

**Comment by mister-ben** [comment]
Sorry, that part of the readme is wrong. Generated by the template I'd used, but doesn't take account that this registers as a tech rather than a plugin. You don't need to call `player.flvjs()`. You do need the flv.js itself as with he script tag instructions, which are correct.
