### ISSUE TITLE
do not work... I have tried this as your md and import bilibili-flv.js, but there are a problem:

### ISSUE THREAD

**Issue by pinglikethinking** [mister-ben/videojs-flvjs#6]
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

my videojs version is "video.js": "^6.2.8",

**Comment by mister-ben** [comment]
There's not really enough information here to say what might be wrong. Try comparing the working example here: https://mister-ben.github.io/videojs-flvjs

**Comment by mister-ben** [comment]
Closing for now as there is not enough detail

**Comment by YOUYOUNG** [comment]
i met the same question at videojs: ^6.6.0
